### PR TITLE
fix specs configuration

### PR DESCRIPTION
**Pull request by Yorkshireman**
- run rails g rspec:install to generate rails_helper
- remove rails_helper code from spec_helper
- fix one model spec

### CODE REVIEW

**Comment by Yorkshireman** [comment]
Hi @knopfler81 - I'll try to resolve this conflict now.

**Comment by Yorkshireman** [comment]
I highly encourage you to question the work I've done and get everything resolved - you should only merge it to your master branch when you're 100% happy with it. Indeed, you may never merge it!

**Comment by Yorkshireman** [comment]
@knopfler81 is your master branch pristine? Does everything work on it fine for you and all its tests pass?

**Comment by Yorkshireman** [comment]
I've rebased the master to this branch and I'm trying to fix the broken tests. I advise that your only job at the moment is to make all the current tests pass. Also:

- never commit failing tests to your master branch. The master branch should *always* be pristine. Develop new features on branches, then either (a) merge that branch to your master branch locally then push your master branch to github or (b) push your branch to github and create a Pull Request with it. If you are the only person working on the repo, the former is fine but if you are collaborating, the latter method should be followed and you have a rule that no-one can merge their own Pull Requests.

**Comment by Yorkshireman** [comment]
ignore commit dc22

**Comment by Yorkshireman** [comment]
That's all the (remaining) tests passing now (when run using `rake spec`, but tests fail when run using `rspec`??).

Will try to fix the deprecation warnings now.

**Comment by Yorkshireman** [comment]
gave up on the deprecation warnings - weird one that.

**Comment by Yorkshireman** [comment]
It's not in a perfect state but it's better than before. Do NOT commit to your master branch with failing tests! I will find out where you live and kick your ass if you do ;-)

**Comment by knopfler81** [comment]
Thanks for all your help I will fix everything tomorrow 👍

**Comment by knopfler81** [comment]
woaaaw you did a big job ! Thanks a lot for all the time you spent helping me !
I will not put failling tests on my master branch I promise

**Pull request merged**
